//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvxScaffolding.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvxScaffolding.Localization.Resources.LocalResources", typeof(LocalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string About_Button_Close {
            get {
                return ResourceManager.GetString("About_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string About_Changelog_Link {
            get {
                return ResourceManager.GetString("About_Changelog_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string About_CreatedBy {
            get {
                return ResourceManager.GetString("About_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A customizable template used to scaffold a cross platform MvvmCross application. Includes a .NET Standard class library and NuGet package references. Supports Xamarin Android, Xamarin iOS and UWP project types for Xamarin Native and Xamarin Forms..
        /// </summary>
        public static string About_General__Desc {
            get {
                return ResourceManager.GetString("About_General__Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For issues and feature requests visit MvxScaffolding project on GitHub..
        /// </summary>
        public static string About_GitHub_Desc {
            get {
                return ResourceManager.GetString("About_GitHub_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string About_GitHub_Link {
            get {
                return ResourceManager.GetString("About_GitHub_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template wizard makes use of 3rd party crash and analytics reporting. See the privacy policy for more information..
        /// </summary>
        public static string About_Privacy_Desc {
            get {
                return ResourceManager.GetString("About_Privacy_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string About_Privacy_Link {
            get {
                return ResourceManager.GetString("About_Privacy_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Translate.
        /// </summary>
        public static string About_Translate_Link {
            get {
                return ResourceManager.GetString("About_Translate_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string AppDetails_Application {
            get {
                return ResourceManager.GetString("AppDetails_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string AppDetails_Display_Name {
            get {
                return ResourceManager.GetString("AppDetails_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditorConfig.
        /// </summary>
        public static string AppDetails_EditorConfig {
            get {
                return ResourceManager.GetString("AppDetails_EditorConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string AppDetails_Identifier {
            get {
                return ResourceManager.GetString("AppDetails_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MvvmCross Version.
        /// </summary>
        public static string AppDetails_MvvmCross_Version {
            get {
                return ResourceManager.GetString("AppDetails_MvvmCross_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Grouping.
        /// </summary>
        public static string AppDetails_Project_Grouping {
            get {
                return ResourceManager.GetString("AppDetails_Project_Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string AppDetails_Required {
            get {
                return ResourceManager.GetString("AppDetails_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string AppDetails_Solution {
            get {
                return ResourceManager.GetString("AppDetails_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name required.
        /// </summary>
        public static string AppDetails_Validation_Display_Name {
            get {
                return ResourceManager.GetString("AppDetails_Validation_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application identifier required.
        /// </summary>
        public static string AppDetails_Validation_Identifier {
            get {
                return ResourceManager.GetString("AppDetails_Validation_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Main_Window_Button_About {
            get {
                return ResourceManager.GetString("Main_Window_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Main_Window_Button_Done {
            get {
                return ResourceManager.GetString("Main_Window_Button_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Main_Window_Button_Next {
            get {
                return ResourceManager.GetString("Main_Window_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Main_Window_Button_Previous {
            get {
                return ResourceManager.GetString("Main_Window_Button_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Main_Window_Button_Privacy {
            get {
                return ResourceManager.GetString("Main_Window_Button_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string Main_Window_Button_Translate {
            get {
                return ResourceManager.GetString("Main_Window_Button_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit MvxScaffolding on GitHub.
        /// </summary>
        public static string Main_Window_Link_GitHub {
            get {
                return ResourceManager.GetString("Main_Window_Link_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string Main_Window_Notify_Dismiss {
            get {
                return ResourceManager.GetString("Main_Window_Notify_Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        public static string Main_Window_Notify_ReleaseNotes {
            get {
                return ResourceManager.GetString("Main_Window_Notify_ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated.
        /// </summary>
        public static string Main_Window_Notify_Updated {
            get {
                return ResourceManager.GetString("Main_Window_Notify_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Details.
        /// </summary>
        public static string Main_Window_SectionHeader_AppDetails {
            get {
                return ResourceManager.GetString("Main_Window_SectionHeader_AppDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platforms Options.
        /// </summary>
        public static string Main_Window_SectionHeader_PlatformOptions {
            get {
                return ResourceManager.GetString("Main_Window_SectionHeader_PlatformOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Main_Window_SectionHeader_Summary {
            get {
                return ResourceManager.GetString("Main_Window_SectionHeader_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Share.
        /// </summary>
        public static string PlatformOptions_Android_MarketShare {
            get {
                return ResourceManager.GetString("PlatformOptions_Android_MarketShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min SDK version.
        /// </summary>
        public static string PlatformOptions_Android_MinSdk {
            get {
                return ResourceManager.GetString("PlatformOptions_Android_MinSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string PlatformOptions_Android_Title {
            get {
                return ResourceManager.GetString("PlatformOptions_Android_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Test Project.
        /// </summary>
        public static string PlatformOptions_Android_UITestProject {
            get {
                return ResourceManager.GetString("PlatformOptions_Android_UITestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Test Project.
        /// </summary>
        public static string PlatformOptions_Android_UnitTestProject {
            get {
                return ResourceManager.GetString("PlatformOptions_Android_UnitTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Layouts.
        /// </summary>
        public static string PlatformOptions_Android_XmlLayouts {
            get {
                return ResourceManager.GetString("PlatformOptions_Android_XmlLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Standard.
        /// </summary>
        public static string PlatformOptions_Core_dotNetStandard {
            get {
                return ResourceManager.GetString("PlatformOptions_Core_dotNetStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string PlatformOptions_Core_Title {
            get {
                return ResourceManager.GetString("PlatformOptions_Core_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Test Project.
        /// </summary>
        public static string PlatformOptions_Core_UnitTestProject {
            get {
                return ResourceManager.GetString("PlatformOptions_Core_UnitTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent Layouts.
        /// </summary>
        public static string PlatformOptions_Ios_FluentLayouts {
            get {
                return ResourceManager.GetString("PlatformOptions_Ios_FluentLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperion.
        /// </summary>
        public static string PlatformOptions_Ios_Hyperion {
            get {
                return ResourceManager.GetString("PlatformOptions_Ios_Hyperion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Share.
        /// </summary>
        public static string PlatformOptions_Ios_MarketShare {
            get {
                return ResourceManager.GetString("PlatformOptions_Ios_MarketShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min SDK version.
        /// </summary>
        public static string PlatformOptions_Ios_MinSdk {
            get {
                return ResourceManager.GetString("PlatformOptions_Ios_MinSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS.
        /// </summary>
        public static string PlatformOptions_Ios_Title {
            get {
                return ResourceManager.GetString("PlatformOptions_Ios_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Test Project.
        /// </summary>
        public static string PlatformOptions_Ios_UITestProject {
            get {
                return ResourceManager.GetString("PlatformOptions_Ios_UITestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Test Project.
        /// </summary>
        public static string PlatformOptions_Ios_UnitTestProject {
            get {
                return ResourceManager.GetString("PlatformOptions_Ios_UnitTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PlatformOptions_Uwp_Description {
            get {
                return ResourceManager.GetString("PlatformOptions_Uwp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Share.
        /// </summary>
        public static string PlatformOptions_Uwp_MarketShare {
            get {
                return ResourceManager.GetString("PlatformOptions_Uwp_MarketShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min SDK version.
        /// </summary>
        public static string PlatformOptions_Uwp_MinSdk {
            get {
                return ResourceManager.GetString("PlatformOptions_Uwp_MinSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP.
        /// </summary>
        public static string PlatformOptions_Uwp_Title {
            get {
                return ResourceManager.GetString("PlatformOptions_Uwp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Test Project.
        /// </summary>
        public static string PlatformOptions_Uwp_UITestProject {
            get {
                return ResourceManager.GetString("PlatformOptions_Uwp_UITestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Test Project.
        /// </summary>
        public static string PlatformOptions_Uwp_UnitTestProject {
            get {
                return ResourceManager.GetString("PlatformOptions_Uwp_UnitTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description required.
        /// </summary>
        public static string PlatformOptions_Validation_Uwp_Description {
            get {
                return ResourceManager.GetString("PlatformOptions_Validation_Uwp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ProjectGrouping_Button_Close {
            get {
                return ResourceManager.GetString("ProjectGrouping_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grouping for projects into folders inside of the solution..
        /// </summary>
        public static string ProjectGrouping_Description {
            get {
                return ResourceManager.GetString("ProjectGrouping_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Flat&quot; for when you want all projects to be placed at the root of the solution..
        /// </summary>
        public static string ProjectGrouping_Select_Flat {
            get {
                return ResourceManager.GetString("ProjectGrouping_Select_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Platform&quot;for when you want projects to be grouped based on their target platform..
        /// </summary>
        public static string ProjectGrouping_Select_Platform {
            get {
                return ResourceManager.GetString("ProjectGrouping_Select_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Test Group&quot; for when you want all test projects to be placed in a test folder, other projects are placed at the root of the solution..
        /// </summary>
        public static string ProjectGrouping_Select_TestGroup {
            get {
                return ResourceManager.GetString("ProjectGrouping_Select_TestGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Grouping.
        /// </summary>
        public static string ProjectGrouping_Title {
            get {
                return ResourceManager.GetString("ProjectGrouping_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ReleaseNotes_Button_Close {
            get {
                return ResourceManager.GetString("ReleaseNotes_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string ReleaseNotes_Changelog_Link {
            get {
                return ResourceManager.GetString("ReleaseNotes_Changelog_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string ReleaseNotes_GitHub_Link {
            get {
                return ResourceManager.GetString("ReleaseNotes_GitHub_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SimpleInfo_Button_Close {
            get {
                return ResourceManager.GetString("SimpleInfo_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string SimpleInfo_Button_More_Info {
            get {
                return ResourceManager.GetString("SimpleInfo_Button_More_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to include an EditorConfig file at the root of the solution. EditorConfig is used to define coding styles highlighted within Visual Studio..
        /// </summary>
        public static string SimpleInfo_EditorConfig_Desc {
            get {
                return ResourceManager.GetString("SimpleInfo_EditorConfig_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditorConfig.
        /// </summary>
        public static string SimpleInfo_EditorConfig_Title {
            get {
                return ResourceManager.GetString("SimpleInfo_EditorConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to include FluentLayout, a fluent API for creating constraint-based layouts..
        /// </summary>
        public static string SimpleInfo_Fluent_Layouts_Desc {
            get {
                return ResourceManager.GetString("SimpleInfo_Fluent_Layouts_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent Layouts.
        /// </summary>
        public static string SimpleInfo_Fluent_Layouts_Title {
            get {
                return ResourceManager.GetString("SimpleInfo_Fluent_Layouts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to include Hyperion, an in app design review tool..
        /// </summary>
        public static string SimpleInfo_Hyperion_Desc {
            get {
                return ResourceManager.GetString("SimpleInfo_Hyperion_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperion.
        /// </summary>
        public static string SimpleInfo_Hyperion_Title {
            get {
                return ResourceManager.GetString("SimpleInfo_Hyperion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template wizard makes use of 3rd party crash and analytics reporting. See the privacy policy for more information..
        /// </summary>
        public static string SimpleInfo_Privacy_Desc {
            get {
                return ResourceManager.GetString("SimpleInfo_Privacy_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string SimpleInfo_Privacy_Title {
            get {
                return ResourceManager.GetString("SimpleInfo_Privacy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an error in spelling or grammar? Want MvxScaffolding translated into your native language? To help translate MvxScaffolding, please visit our Crowdin page..
        /// </summary>
        public static string SimpleInfo_Translate_Desc {
            get {
                return ResourceManager.GetString("SimpleInfo_Translate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Translate.
        /// </summary>
        public static string SimpleInfo_Translate_Title {
            get {
                return ResourceManager.GetString("SimpleInfo_Translate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to use XML layouts instead of Xamarin default AXML layouts..
        /// </summary>
        public static string SimpleInfo_Xml_Layouts_Desc {
            get {
                return ResourceManager.GetString("SimpleInfo_Xml_Layouts_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Layouts.
        /// </summary>
        public static string SimpleInfo_Xml_Layouts_Title {
            get {
                return ResourceManager.GetString("SimpleInfo_Xml_Layouts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min SDK version.
        /// </summary>
        public static string Summary_Android_MinSdk {
            get {
                return ResourceManager.GetString("Summary_Android_MinSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string Summary_Android_Title {
            get {
                return ResourceManager.GetString("Summary_Android_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Test Project.
        /// </summary>
        public static string Summary_Android_UITestProject {
            get {
                return ResourceManager.GetString("Summary_Android_UITestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Test Project.
        /// </summary>
        public static string Summary_Android_UnitTestProject {
            get {
                return ResourceManager.GetString("Summary_Android_UnitTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Layouts.
        /// </summary>
        public static string Summary_Android_XmlLayouts {
            get {
                return ResourceManager.GetString("Summary_Android_XmlLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Summary_Application {
            get {
                return ResourceManager.GetString("Summary_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Standard.
        /// </summary>
        public static string Summary_Core_dotNetStandard {
            get {
                return ResourceManager.GetString("Summary_Core_dotNetStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string Summary_Core_Title {
            get {
                return ResourceManager.GetString("Summary_Core_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Test Project.
        /// </summary>
        public static string Summary_Core_UnitTestProject {
            get {
                return ResourceManager.GetString("Summary_Core_UnitTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Summary_DisplayName {
            get {
                return ResourceManager.GetString("Summary_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditorConfig.
        /// </summary>
        public static string Summary_EditorConfig {
            get {
                return ResourceManager.GetString("Summary_EditorConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string Summary_Identifier {
            get {
                return ResourceManager.GetString("Summary_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS.
        /// </summary>
        public static string Summary_Ios {
            get {
                return ResourceManager.GetString("Summary_Ios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent Layouts.
        /// </summary>
        public static string Summary_Ios_FluentLayouts {
            get {
                return ResourceManager.GetString("Summary_Ios_FluentLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperion.
        /// </summary>
        public static string Summary_Ios_Hyperion {
            get {
                return ResourceManager.GetString("Summary_Ios_Hyperion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min SDK version.
        /// </summary>
        public static string Summary_Ios_MinSdk {
            get {
                return ResourceManager.GetString("Summary_Ios_MinSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Test Project.
        /// </summary>
        public static string Summary_Ios_UITestProject {
            get {
                return ResourceManager.GetString("Summary_Ios_UITestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Test Project.
        /// </summary>
        public static string Summary_Ios_UnitTestProject {
            get {
                return ResourceManager.GetString("Summary_Ios_UnitTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Grouping.
        /// </summary>
        public static string Summary_ProjectGrouping {
            get {
                return ResourceManager.GetString("Summary_ProjectGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Summary_Uwp_Description {
            get {
                return ResourceManager.GetString("Summary_Uwp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min SDK version.
        /// </summary>
        public static string Summary_Uwp_MinSdk {
            get {
                return ResourceManager.GetString("Summary_Uwp_MinSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP.
        /// </summary>
        public static string Summary_Uwp_Title {
            get {
                return ResourceManager.GetString("Summary_Uwp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Test Project.
        /// </summary>
        public static string Summary_Uwp_UITestProject {
            get {
                return ResourceManager.GetString("Summary_Uwp_UITestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Test Project.
        /// </summary>
        public static string Summary_Uwp_UnitTestProject {
            get {
                return ResourceManager.GetString("Summary_Uwp_UnitTestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string Template_Choice_False {
            get {
                return ResourceManager.GetString("Template_Choice_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        public static string Template_Choice_ProjectGroup_Flat {
            get {
                return ResourceManager.GetString("Template_Choice_ProjectGroup_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string Template_Choice_ProjectGroup_Platform {
            get {
                return ResourceManager.GetString("Template_Choice_ProjectGroup_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Group.
        /// </summary>
        public static string Template_Choice_ProjectGroup_TestGroup {
            get {
                return ResourceManager.GetString("Template_Choice_ProjectGroup_TestGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string Template_Choice_True {
            get {
                return ResourceManager.GetString("Template_Choice_True", resourceCulture);
            }
        }
    }
}
