# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/MvxScaffolding.sln'
  buildProject: '**/MvxScaffolding.Vsix.csproj'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Install NuGet'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'Restore NuGets'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    displayName: 'Build VSIX'
    solution: '$(buildProject)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
