# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-2019'

name: $(Build.BuildId)

variables:
  solution: '**/MvxScaffolding.Vsix.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Install NuGet'
  inputs:
    versionSpec: 5.6.0

- task: Cake@2
  inputs:
    script: 'build.cake'
    target: 'Default'
    verbosity: 'Verbose'
  displayName: 'Cake Build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Vsix-drop'
  inputs:
    PathtoPublish: 'artifacts/Vsix'
    ArtifactName: 'Build-Vsix'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: NuGet-drop'
  inputs:
    PathtoPublish: './artifacts/NuGet'
    ArtifactName: 'Build-NuGet'


